# NuroPadel Resilient Docker Compose - Independent Service Deployment
# Each service can deploy independently - failed services won't block working ones

services:
  # === YOLO Combined Service (YOLO11 + YOLOv8) ===
  yolo-combined:
    profiles: ["yolo-combined", "all"]
    build:
      context: ./yolo-combined-service
      dockerfile: Dockerfile
    image: nuro-padel/yolo-combined:latest
    container_name: nuro-padel-yolo-combined
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - nuro-padel-network

  # === MMPose Biomechanics Service ===
  mmpose:
    profiles: ["mmpose", "all"]
    build:
      context: ./mmpose-service
      dockerfile: Dockerfile
    image: nuro-padel/mmpose:latest
    container_name: nuro-padel-mmpose
    restart: unless-stopped
    ports:
      - "8003:8003"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - nuro-padel-network

  # === YOLO-NAS High-Accuracy Service ===
  yolo-nas:
    profiles: ["yolo-nas", "all"]
    build:
      context: ./yolo-nas-service
      dockerfile: Dockerfile
    image: nuro-padel/yolo-nas:latest
    container_name: nuro-padel-yolo-nas
    restart: unless-stopped
    ports:
      - "8004:8004"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - nuro-padel-network

  # === Resilient Nginx Load Balancer ===
  nginx:
    profiles: ["nginx", "all"]
    image: nginx:alpine
    container_name: nuro-padel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.resilient.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    # NO depends_on - let nginx handle missing services gracefully
    networks:
      - nuro-padel-network

networks:
  nuro-padel-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  weights-data:
    driver: local