# NuroPadel Test Docker Compose - For GitHub Actions CI/CD
# Uses pre-built images from GitHub Container Registry

services:
  # === YOLO Combined Service (YOLO11 + YOLOv8) ===
  yolo-combined:
    image: ${REGISTRY}/yolo-combined:latest
    container_name: nuro-padel-yolo-combined-test
    ports:
      - "8001:8001"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Fix permission/directory issues
      - HOME=/tmp
      - MPLCONFIGDIR=/tmp/matplotlib
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - nuro-padel-test-network

  # === MMPose Biomechanics Service ===
  mmpose:
    image: ${REGISTRY}/mmpose:latest
    container_name: nuro-padel-mmpose-test
    ports:
      - "8003:8003"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Fix permission/directory issues
      - HOME=/tmp
      - MPLCONFIGDIR=/tmp/matplotlib
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - nuro-padel-test-network

  # === YOLO-NAS High-Accuracy Service ===
  yolo-nas:
    image: ${REGISTRY}/yolo-nas:latest
    container_name: nuro-padel-yolo-nas-test
    ports:
      - "8004:8004"
    volumes:
      - ./weights:/app/weights:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Fix permission/directory issues
      - HOME=/tmp
      - MPLCONFIGDIR=/tmp/matplotlib
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - nuro-padel-test-network

  # === Nginx Load Balancer & Reverse Proxy ===
  nginx:
    image: nginx:alpine
    container_name: nuro-padel-nginx-test
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - yolo-combined
      - mmpose
      - yolo-nas
    networks:
      - nuro-padel-test-network

networks:
  nuro-padel-test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16