# NuroPadel Docker Compose - Production Deployment
# 3 Isolated AI Services: YOLO Combined, MMPose, YOLO-NAS

version: '3.8'

services:
  # === YOLO Combined Service (YOLO11 + YOLOv8) ===
  yolo-combined:
    build:
      context: ../services/yolo-combined
      dockerfile: Dockerfile
    image: ghcr.io/stevetowers098/nuro-padel/yolo-combined:latest
    container_name: nuro-padel-yolo-combined
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8001:8001"
    volumes:
      - /opt/padel-docker/weights:/app/weights:ro
      - ../services/yolo-combined/config:/app/config:ro
      - ../services/shared:/app/shared:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      # Model configuration overrides (examples)
      # - YOLO11_POSE_ENABLED=true
      # - FEATURE_ENHANCED_BALL_TRACKING_ENABLED=true
      # - CONFIDENCE_THRESHOLD=0.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - nuro-padel-network

  # === MMPose Biomechanics Service ===
  mmpose:
    build:
      context: ../services/mmpose
      dockerfile: Dockerfile
    image: ghcr.io/stevetowers098/nuro-padel/mmpose:latest
    container_name: nuro-padel-mmpose
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8003:8003"
    volumes:
      - /opt/padel-docker/weights:/app/weights:ro
      - ../services/mmpose/configs:/app/configs:ro
      - ../services/mmpose/config:/app/config:ro
      - ../services/shared:/app/shared:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      # Model configuration overrides (examples)
      # - RTMPOSE_M_ENABLED=true
      # - FEATURE_BIOMECHANICAL_ANALYSIS_ENABLED=true
      # - FEATURE_3D_POSE_ESTIMATION_ENABLED=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - nuro-padel-network

  # === YOLO-NAS High-Accuracy Service ===
  yolo-nas:
    build:
      context: ../services/yolo-nas
      dockerfile: Dockerfile
    image: ghcr.io/stevetowers098/nuro-padel/yolo-nas:latest
    container_name: nuro-padel-yolo-nas
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8004:8004"
    volumes:
      - /opt/padel-docker/weights:/app/weights:ro
      - ../services/yolo-nas/config:/app/config:ro
      - ../services/shared:/app/shared:ro
      - /tmp:/tmp
    environment:
      - YOLO_OFFLINE=1
      - ULTRALYTICS_OFFLINE=1
      - ONLINE=False
      - YOLO_TELEMETRY=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      # Model configuration overrides (examples)
      # - YOLO_NAS_S_ENABLED=true
      # - FEATURE_HIGH_ACCURACY_MODE_ENABLED=true
      # - FEATURE_ONNX_OPTIMIZATION_ENABLED=true
      # - FEATURE_TENSORRT_OPTIMIZATION_ENABLED=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - nuro-padel-network

  # === Nginx Load Balancer & Reverse Proxy ===
  nginx:
    image: nginx:alpine
    container_name: nuro-padel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - yolo-combined
      - mmpose
      - yolo-nas
    networks:
      - nuro-padel-network

networks:
  nuro-padel-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  weights-data:
    driver: local